# -*- coding: utf-8 -*-
"""Bri_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IL5Shc8VBI_BNh5qEOehwkmp2SgTXxiL
"""

import streamlit as st

st.title('Hello Wilders, welcome to my application!')