# -*- coding: utf-8 -*-
"""Bri_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IL5Shc8VBI_BNh5qEOehwkmp2SgTXxiL
"""

import streamlit as st

# PAGE TITLE
st.set_page_config(page_title="quête semaine 17", layout='wide')
st.title('Hello Wilders, welcome to my application!')
st.write("test mia-à-jour")
